name = "REDFLASHLIGHT"
prefix = "redflashlight"
author = "kolmipilot"
mainprefix = "z"


[files]
include = [
    "mod.cpp",
    "README.md",
    "LICENSE.md",
    "modicon_ico.paa"
]

[version]
git_hash = 0
